services:
  - type: web
    name: find-cnpj
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BIGDATA_TOKEN_ID
        sync: false
      - key: BIGDATA_TOKEN_HASH
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 